version: '3'

services:
  target:
    image: postgres:latest
    container_name: data_load
    environment:
      POSTGRES_DB: store_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - 5436:5432
    volumes:
      - ./data:/docker-entrypoint-initdb.d

    source:
      image: postgres:latest
      container_name: sales_data
      environment:
        POSTGRES_DB: etl_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password123
      ports:
        - 5434:5432