version: '3'

services:
  target:
    image: postgres:latest
    container_name: data_load
    environment:
      POSTGRES_DB: store_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - 5436:5432
    volumes:
      - ./data:/docker-entrypoint-initdb.d